"""Pydantic schemas for team composition."""

from __future__ import annotations

from pydantic import BaseModel, Field

from schemas.matching import CandidateMatch, EvidenceItem, ProjectFitWeights


class TeamValidation(BaseModel):
    """Post-composition team validation results."""

    skill_coverage_percentage: float  # 0–100
    covered_skills: list[str] = []
    missing_skills: list[str] = []
    role_coverage: list[str] = []
    domain_coverage: list[str] = []
    availability_satisfied: bool
    has_redundancy: bool
    redundant_skills: list[str] = []
    risks: list[str] = []
    warnings: list[str] = []


class RecommendedTeam(BaseModel):
    """Final recommended complementary team."""

    project_id: int | None = None
    members: list[CandidateMatch] = []

    # Explanation generated by LLM (marked as inference, not fact)
    explanation: str = ""
    explanation_source: str = "llm_inference"

    # Evidence from Hindsight that influenced team composition
    hindsight_evidence: list[EvidenceItem] = []

    # RAG evidence from company documentation
    rag_evidence: list[EvidenceItem] = []

    # Validation
    validation: TeamValidation | None = None

    # Weights used for scoring
    weights_used: ProjectFitWeights = Field(default_factory=ProjectFitWeights)

    # Were Hindsight memories found?
    hindsight_memories_found: bool = False
    no_memory_message: str | None = None  # Shown if no memories found
